import { CalculationMethod, Coordinates, HighLatitudeRule, Madhab, PrayerTimes } from "adhan";
import { assertPrayerCalculationRequest, assertPrayerCalculationResult, ProductionAdapterError } from "../application/production-adapter-contracts.js";
import type { PrayerCalculationAdapter, PrayerCalculationRequest, PrayerCalculationResult } from "../application/production-adapter-contracts.js";
import type { LocalDate, LocationProfileRevision, PrayerCalculation, PrayerTimePolicyRevision } from "../domain/model.js";
import type { PrayerTimeCalculatorPort } from "../ports.js";
const methods = { MuslimWorldLeague: CalculationMethod.MuslimWorldLeague, Egyptian: CalculationMethod.Egyptian, Karachi: CalculationMethod.Karachi, UmmAlQura: CalculationMethod.UmmAlQura, NorthAmerica: CalculationMethod.NorthAmerica } as const;
function noon(value: string): Date { if (!/^\d{4}-\d{2}-\d{2}$/u.test(value)) throw new ProductionAdapterError("UnsupportedPrayerDate", "Invalid civil date."); const [y,m,d] = value.split("-").map(Number); const date = new Date(`${value}T12:00:00.000`); if (!Number.isFinite(date.getTime()) || date.getFullYear() !== y || date.getMonth()+1 !== m || date.getDate() !== d) throw new ProductionAdapterError("UnsupportedPrayerDate", "Unsupported civil date."); return date; }
export class AdhanPrayerCalculationAdapter implements PrayerCalculationAdapter { readonly kind = "PrayerCalculation" as const; async calculate(r: PrayerCalculationRequest): Promise<PrayerCalculationResult> { assertPrayerCalculationRequest(r); const factory = methods[r.calculationMethod as keyof typeof methods]; if (!factory || r.asrMethod !== "standard" || r.highLatitudeRule !== "middle-of-night" || r.engineVersion !== "4.4.4") throw new ProductionAdapterError("UnsupportedPrayerPolicy", "Unsupported frozen prayer policy."); try { const p = factory(); p.madhab = Madhab.Shafi; p.highLatitudeRule = HighLatitudeRule.MiddleOfTheNight; const x = new PrayerTimes(new Coordinates(r.latitude,r.longitude), noon(r.civilDate), p); const result: PrayerCalculationResult = { requestedCivilDate:r.civilDate,timeZone:r.timeZone,latitude:r.latitude,longitude:r.longitude,calculationMethod:r.calculationMethod,asrMethod:r.asrMethod,highLatitudeRule:r.highLatitudeRule,engineName:"adhan",engineVersion:"4.4.4",fajr:x.fajr.toISOString(),sunrise:x.sunrise.toISOString(),dhuhr:x.dhuhr.toISOString(),asr:x.asr.toISOString(),maghrib:x.maghrib.toISOString(),isha:x.isha.toISOString() }; assertPrayerCalculationResult(r,result); return result; } catch (error) { if (error instanceof ProductionAdapterError) throw error; throw new ProductionAdapterError("PrayerCalculationUnavailable", "Prayer calculation is unavailable.", { cause:error }); } } }
export class AdhanPrayerTimeCalculator implements PrayerTimeCalculatorPort { public constructor(private readonly adapter: PrayerCalculationAdapter = new AdhanPrayerCalculationAdapter()) {} async calculate(location: LocationProfileRevision, policy: PrayerTimePolicyRevision, localDate: LocalDate): Promise<PrayerCalculation> { const r = await this.adapter.calculate({civilDate:localDate,timeZone:location.timeZone,latitude:location.latitude,longitude:location.longitude,calculationMethod:policy.calculationMethod,asrMethod:"standard",highLatitudeRule:"middle-of-night",engineVersion:"4.4.4"}); return {localDate,fajr:r.fajr,sunrise:r.sunrise,dhuhr:r.dhuhr,asr:r.asr,maghrib:r.maghrib,isha:r.isha,source:r.engineName,engineVersion:r.engineVersion}; } }
