export const EXECUTION_DESIGN_DOMAINS=["Execution Authorization and Scope","Registration Request Envelope","Registrar Identity and Authority","Independent Reviewer Identity and Authority","Candidate Revision and Concurrency Control","Foundation Schema Validation","Dry-Run Evaluation","Quarantine and Blocking Findings","Evidence Reference Admission","Capability and Privilege Admission","Dependency and Supply-Chain Admission","Duplicate Alias and Supersession Resolution","Lifecycle Transition Evaluation","Canonical Serialization","Registration Seal Production","Decision Record and Audit Trail","Withdrawal Revocation and Revalidation","Repository Non-Mutation and Publication Boundary"] as const;
export const EXECUTION_PHASES=["OE-01_AUTHORIZATION_SEAL_VERIFICATION","OE-02_REQUEST_ENVELOPE_ADMISSION","OE-03_REGISTRAR_AUTHORITY_VERIFICATION","OE-04_INDEPENDENT_REVIEWER_ASSIGNMENT","OE-05_CANDIDATE_REVISION_LOCK","OE-06_FOUNDATION_SCHEMA_VALIDATION","OE-07_IDENTITY_AND_LINEAGE_VALIDATION","OE-08_PROVENANCE_LICENSE_AND_LIFECYCLE_VALIDATION","OE-09_CAPABILITY_PRIVILEGE_AND_HOST_VALIDATION","OE-10_DEPENDENCY_AND_SUPPLY_CHAIN_VALIDATION","OE-11_EVIDENCE_REFERENCE_ADMISSION_VALIDATION","OE-12_DUPLICATE_ALIAS_AND_SUPERSESSION_RESOLUTION","OE-13_DRY_RUN_GATE_EVALUATION","OE-14_QUARANTINE_OR_REVIEW_READY_DECISION","OE-15_CANONICAL_REGISTRATION_PROJECTION","OE-16_SEAL_AND_DECISION_PROJECTION","OE-17_INDEPENDENT_APPROVAL_OR_REJECTION_PROJECTION"] as const;
export const EXECUTION_GATES=["EG-01_EXECUTION_AUTHORIZATION_AND_SCOPE","EG-02_REGISTRATION_REQUEST_ENVELOPE","EG-03_REGISTRAR_IDENTITY_AND_AUTHORITY","EG-04_INDEPENDENT_REVIEWER_IDENTITY_AND_AUTHORITY","EG-05_CANDIDATE_REVISION_AND_CONCURRENCY_CONTROL","EG-06_FOUNDATION_SCHEMA_VALIDATION","EG-07_DRY_RUN_EVALUATION","EG-08_QUARANTINE_AND_BLOCKING_FINDINGS","EG-09_EVIDENCE_REFERENCE_ADMISSION","EG-10_CAPABILITY_AND_PRIVILEGE_ADMISSION","EG-11_DEPENDENCY_AND_SUPPLY_CHAIN_ADMISSION","EG-12_DUPLICATE_ALIAS_AND_SUPERSESSION_RESOLUTION","EG-13_LIFECYCLE_TRANSITION_EVALUATION","EG-14_CANONICAL_SERIALIZATION","EG-15_REGISTRATION_SEAL_PRODUCTION","EG-16_DECISION_RECORD_AND_AUDIT_TRAIL","EG-17_WITHDRAWAL_REVOCATION_AND_REVALIDATION","EG-18_REPOSITORY_NON_MUTATION_AND_PUBLICATION_BOUNDARY"] as const;
export const EXECUTION_OUTCOMES=["EXECUTION_REJECTED","QUARANTINED","REVIEW_READY_PROJECTED","APPROVAL_PROJECTED","REJECTION_PROJECTED","REVALIDATION_REQUIRED"] as const;
export const FAILURE_CODES=["AUTHORIZATION_MISSING","SCOPE_VIOLATION","REQUEST_ID_INVALID","IDEMPOTENCY_KEY_INVALID","REQUEST_EXPIRED","PURPOSE_INVALID","REGISTRAR_ID_INVALID","REVIEWER_ID_INVALID","SELF_REVIEW_FORBIDDEN","REGISTRAR_AUTHORITY_MISSING","REVIEWER_AUTHORITY_MISSING","FOUNDATION_SEAL_MISMATCH","CANDIDATE_ID_INVALID","REVISION_ID_INVALID","CONCURRENCY_CONFLICT","DOMAIN_BINDING_INVALID","CONCEPT_FAMILY_INVALID","DECLARATIONS_INCOMPLETE","CAPABILITY_ADMISSION_BLOCKED","PRIVILEGE_ADMISSION_BLOCKED","DEPENDENCY_ADMISSION_BLOCKED","SUPPLY_CHAIN_ADMISSION_BLOCKED","EVIDENCE_ADMISSION_BLOCKED","DUPLICATE_ALIAS_CONFLICT","SUPERSESSION_INVALID","LIFECYCLE_INVALID","BLOCKING_FINDINGS_PRESENT","GATE_NOT_READY","DRY_RUN_ONLY_VIOLATION","OPERATIONAL_REGISTRATION_FORBIDDEN","MANIFEST_PERSISTENCE_FORBIDDEN","STATE_TRANSITION_FORBIDDEN","PERSISTENT_DECISION_FORBIDDEN","PERSISTENT_SEAL_FORBIDDEN","CANONICALIZATION_FAILURE","TRANSIENT_SEAL_MISMATCH","REPOSITORY_MUTATION_DETECTED"] as const;
export const CONCEPT_FAMILIES=["NATIVE","DECLARATIVE","ISOLATED","OFFLINE"] as const;
export type ExecutionDomain=(typeof EXECUTION_DESIGN_DOMAINS)[number];
export type ExecutionOutcome=(typeof EXECUTION_OUTCOMES)[number];
export type FailureCode=(typeof FAILURE_CODES)[number];
export type ConceptFamily=(typeof CONCEPT_FAMILIES)[number];
export interface RegistrationExecutionRequest{requestId:string;idempotencyKey:string;purpose:string;issuedAt:string;expiresAt:string;candidateId:string;revisionId:string;expectedPriorRevisionId:string|null;registrarId:string;reviewerId:string;foundationSeal:string;dryRunOnly:true;}
export interface AuthorityContext{executionFoundationAuthorized:boolean;registrarAuthorized:boolean;reviewerAuthorized:boolean;scope:string;authorizationExpiresAt:string;}
export interface CandidateRevisionProjection{candidateId:string;revisionId:string;priorRevisionId:string|null;controlDomain:string;conceptFamily:string;declarationsComplete:boolean;capabilitiesAdmissible:boolean;privilegesAdmissible:boolean;dependenciesAdmissible:boolean;supplyChainAdmissible:boolean;evidenceReferencesAdmissible:boolean;duplicatesResolved:boolean;supersessionValid:boolean;lifecycleValid:boolean;blockingFindings:readonly string[];}
export interface ExecutionInput{request:RegistrationExecutionRequest;authority:AuthorityContext;candidate:CandidateRevisionProjection;expectedFoundationSeal:string;now:string;repositoryMutationDetected:boolean;operationalEffectRequested?:boolean;manifestPersistenceRequested?:boolean;stateTransitionRequested?:boolean;persistentDecisionRequested?:boolean;persistentSealRequested?:boolean;}
export interface DryRunProjection{requestId:string;candidateId:string;revisionId:string;outcome:ExecutionOutcome;failedGates:readonly string[];blockingFindings:readonly string[];canonicalProjection:string;transientSeal:string;operationalEffect:false;}
export class ExecutionFoundationError extends Error{readonly code:FailureCode;constructor(code:FailureCode,message:string){super(message);this.name="ExecutionFoundationError";this.code=code;}}
const ID=/^[A-Za-z][A-Za-z0-9._:-]{2,127}$/;const ISO=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
function fail(code:FailureCode,message:string):never{throw new ExecutionFoundationError(code,message)}
function req(value:string,code:FailureCode,message:string):void{if(!value.trim())fail(code,message)}
function iso(value:string,code:FailureCode):number{if(!ISO.test(value))fail(code,"Invalid UTC timestamp.");const parsed=Date.parse(value);if(!Number.isFinite(parsed))fail(code,"Invalid UTC timestamp.");return parsed}
export function validateExecutionRequest(value:RegistrationExecutionRequest,now:string):void{if(!ID.test(value.requestId))fail("REQUEST_ID_INVALID","Invalid request identity.");if(!ID.test(value.idempotencyKey))fail("IDEMPOTENCY_KEY_INVALID","Invalid idempotency key.");req(value.purpose,"PURPOSE_INVALID","Purpose is required.");if(!ID.test(value.candidateId))fail("CANDIDATE_ID_INVALID","Invalid candidate identity.");if(!ID.test(value.revisionId))fail("REVISION_ID_INVALID","Invalid revision identity.");if(!ID.test(value.registrarId))fail("REGISTRAR_ID_INVALID","Invalid registrar identity.");if(!ID.test(value.reviewerId))fail("REVIEWER_ID_INVALID","Invalid reviewer identity.");if(value.registrarId===value.reviewerId)fail("SELF_REVIEW_FORBIDDEN","Registrar and reviewer must differ.");req(value.foundationSeal,"FOUNDATION_SEAL_MISMATCH","Foundation seal is required.");if(value.dryRunOnly!==true)fail("DRY_RUN_ONLY_VIOLATION","Only dry-run projection is permitted.");const issued=iso(value.issuedAt,"REQUEST_EXPIRED");const expires=iso(value.expiresAt,"REQUEST_EXPIRED");const current=iso(now,"REQUEST_EXPIRED");if(issued>current||expires<=current||expires<=issued)fail("REQUEST_EXPIRED","Request time window is invalid or expired.")}
export function validateAuthority(value:AuthorityContext,request:RegistrationExecutionRequest,now:string):void{if(!value.executionFoundationAuthorized)fail("AUTHORIZATION_MISSING","Execution Foundation authority is missing.");if(!value.registrarAuthorized)fail("REGISTRAR_AUTHORITY_MISSING","Registrar authority is missing.");if(!value.reviewerAuthorized)fail("REVIEWER_AUTHORITY_MISSING","Reviewer authority is missing.");if(value.scope!=="OPERATIONAL_REGISTRATION_EXECUTION_DRY_RUN")fail("SCOPE_VIOLATION","Authority scope is invalid.");if(iso(value.authorizationExpiresAt,"AUTHORIZATION_MISSING")<=iso(now,"AUTHORIZATION_MISSING"))fail("AUTHORIZATION_MISSING","Authority is expired.");if(request.registrarId===request.reviewerId)fail("SELF_REVIEW_FORBIDDEN","Self-review is forbidden.")}
export function validateCandidateProjection(value:CandidateRevisionProjection,request:RegistrationExecutionRequest):void{if(value.candidateId!==request.candidateId)fail("CANDIDATE_ID_INVALID","Candidate identity mismatch.");if(value.revisionId!==request.revisionId)fail("REVISION_ID_INVALID","Revision identity mismatch.");if(value.priorRevisionId!==request.expectedPriorRevisionId)fail("CONCURRENCY_CONFLICT","Expected prior revision mismatch.");if(!EXECUTION_DESIGN_DOMAINS.includes(value.controlDomain as ExecutionDomain))fail("DOMAIN_BINDING_INVALID","Invalid execution domain.");if(!CONCEPT_FAMILIES.includes(value.conceptFamily as ConceptFamily))fail("CONCEPT_FAMILY_INVALID","Invalid concept family.");if(!value.declarationsComplete)fail("DECLARATIONS_INCOMPLETE","Declarations are incomplete.");if(!value.capabilitiesAdmissible)fail("CAPABILITY_ADMISSION_BLOCKED","Capability admission failed.");if(!value.privilegesAdmissible)fail("PRIVILEGE_ADMISSION_BLOCKED","Privilege admission failed.");if(!value.dependenciesAdmissible)fail("DEPENDENCY_ADMISSION_BLOCKED","Dependency admission failed.");if(!value.supplyChainAdmissible)fail("SUPPLY_CHAIN_ADMISSION_BLOCKED","Supply-chain admission failed.");if(!value.evidenceReferencesAdmissible)fail("EVIDENCE_ADMISSION_BLOCKED","Evidence reference admission failed.");if(!value.duplicatesResolved)fail("DUPLICATE_ALIAS_CONFLICT","Duplicate or alias conflict remains.");if(!value.supersessionValid)fail("SUPERSESSION_INVALID","Supersession is invalid.");if(!value.lifecycleValid)fail("LIFECYCLE_INVALID","Lifecycle declaration is invalid.")}
function stable(value:unknown):unknown{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==="object"){const out:Record<string,unknown>={};for(const key of Object.keys(value as Record<string,unknown>).sort())out[key]=stable((value as Record<string,unknown>)[key]);return out}return value}
export function canonicalizeExecutionProjection(value:unknown):string{try{return JSON.stringify(stable(value))}catch{fail("CANONICALIZATION_FAILURE","Projection canonicalization failed.")}}
export function transientContentSeal(canonical:string):string{let hash=BigInt("14695981039346656037");const prime=BigInt("1099511628211");for(const byte of new TextEncoder().encode(canonical)){hash^=BigInt(byte);hash=BigInt.asUintN(64,hash*prime)}return "FNV1A64:"+hash.toString(16).padStart(16,"0")}
function prohibitEffects(input:ExecutionInput):void{if(input.operationalEffectRequested)fail("OPERATIONAL_REGISTRATION_FORBIDDEN","Operational registration is forbidden.");if(input.manifestPersistenceRequested)fail("MANIFEST_PERSISTENCE_FORBIDDEN","Manifest persistence is forbidden.");if(input.stateTransitionRequested)fail("STATE_TRANSITION_FORBIDDEN","Candidate state transition is forbidden.");if(input.persistentDecisionRequested)fail("PERSISTENT_DECISION_FORBIDDEN","Persistent decision creation is forbidden.");if(input.persistentSealRequested)fail("PERSISTENT_SEAL_FORBIDDEN","Persistent seal creation is forbidden.");if(input.repositoryMutationDetected)fail("REPOSITORY_MUTATION_DETECTED","Repository mutation detected.")}
export function projectRegistrationExecution(input:ExecutionInput):DryRunProjection{prohibitEffects(input);validateExecutionRequest(input.request,input.now);validateAuthority(input.authority,input.request,input.now);if(input.request.foundationSeal!==input.expectedFoundationSeal)fail("FOUNDATION_SEAL_MISMATCH","Foundation seal mismatch.");const failed:string[]=[];try{validateCandidateProjection(input.candidate,input.request)}catch(error){if(error instanceof ExecutionFoundationError)failed.push(error.code);else throw error}const findings=[...input.candidate.blockingFindings];if(findings.length)failed.push("BLOCKING_FINDINGS_PRESENT");const outcome:ExecutionOutcome=failed.length?"QUARANTINED":"REVIEW_READY_PROJECTED";const base={requestId:input.request.requestId,candidateId:input.request.candidateId,revisionId:input.request.revisionId,outcome,failedGates:[...new Set(failed)].sort(),blockingFindings:findings.slice().sort(),operationalEffect:false as const};const canonicalProjection=canonicalizeExecutionProjection(base);return {...base,canonicalProjection,transientSeal:transientContentSeal(canonicalProjection)}}
export function projectIndependentDecision(value:DryRunProjection,decision:"APPROVE"|"REJECT"|"REVALIDATE"):DryRunProjection{if(value.outcome!=="REVIEW_READY_PROJECTED"&&decision!=="REVALIDATE")fail("GATE_NOT_READY","Projection is not review ready.");const outcome:ExecutionOutcome=decision==="APPROVE"?"APPROVAL_PROJECTED":decision==="REJECT"?"REJECTION_PROJECTED":"REVALIDATION_REQUIRED";const base={requestId:value.requestId,candidateId:value.candidateId,revisionId:value.revisionId,outcome,failedGates:value.failedGates,blockingFindings:value.blockingFindings,operationalEffect:false as const};const canonicalProjection=canonicalizeExecutionProjection(base);return {...base,canonicalProjection,transientSeal:transientContentSeal(canonicalProjection)}}
export function verifyTransientSeal(value:DryRunProjection):void{if(transientContentSeal(value.canonicalProjection)!==value.transientSeal)fail("TRANSIENT_SEAL_MISMATCH","Transient seal mismatch.")}
export function executeOperationalRegistration():never{return fail("OPERATIONAL_REGISTRATION_FORBIDDEN","Operational registration remains unauthorized.")}
export function persistRegistrationManifest():never{return fail("MANIFEST_PERSISTENCE_FORBIDDEN","Manifest persistence remains unauthorized.")}
