import assert from "node:assert/strict";
import * as A from "../dist/index.js";
const scope={subject:"SYNTHETIC-SUBJECT",purpose:"CONTROLLED_SYNTHETIC_EXECUTION_RUN_AUTHORIZATION_FOUNDATION",capabilities:["PROJECT"],leastPrivilege:true,syntheticBundle:"BUNDLE",catalog:"CATALOG",executor:"RESTRICTED",callback:"PURE",workspace:"EPHEMERAL",environment:"DETERMINISTIC",resourceBudget:"BOUNDED",invocationPlan:"PLAN",scenarios:["S1"],repetitions:1,capture:"SUPPLIED",oracle:"TEST",quarantine:"REQUIRED",abort:"BOUND",cancellation:"BOUND",cleanup:"REQUIRED",replay:"REQUIRED"};
const lifecycle={issuedAt:"2026-07-27T00:00:00Z",activatesAt:"2026-07-27T01:00:00Z",expiresAt:"2026-07-29T00:00:00Z",suspended:false,revoked:false,renewalRequested:false};
const envelope={authoritySource:"REVIEW-042-R1",requestId:"REQUEST-043",revision:"1",immutable:true,requester:{id:"R",role:"REQUESTER"},executorOwner:{id:"E",role:"EXECUTOR_OWNER"},reviewer:{id:"V",role:"REVIEWER"},approver:{id:"A",role:"APPROVER"},scope,seals:{foundation:"FOUNDATION",policy:"POLICY-01",request:"REQUEST-01",subject:"SUBJECT-01",scope:"SCOPE-001"},lifecycle,delegationAllowed:false,transferable:false,conflictOfInterest:false,ambiguousPrecedence:false,operationalEffects:false,persistence:false};
let cases=0;const test=(f)=>{cases++;f()};const code=(patch,c)=>test(()=>{let x;try{A.validateAuthorizationEnvelope({...envelope,...patch})}catch(e){x=e}assert.equal(x?.code,c)});
test(()=>{assert.deepEqual([A.AUTHORIZATION_DOMAINS.length,A.AUTHORIZATION_PHASES.length,A.AUTHORIZATION_GATES.length,A.AUTHORIZATION_OUTCOMES.length],[18,22,18,11])});
test(()=>A.validateAuthorizationEnvelope(envelope));
test(()=>assert.equal(A.canonicalizeAuthorization({b:1,a:2}),A.canonicalizeAuthorization({a:2,b:1})));
test(()=>assert.equal(A.transientAuthorizationSeal("x"),A.transientAuthorizationSeal("x")));
const p=A.projectAuthorizationReadiness(envelope);
test(()=>assert.equal(p.gateStates.length,18));
test(()=>assert.ok(p.gateStates.every(g=>g.state==="PROJECTION_ONLY")));
test(()=>assert.ok(Object.values(p.operationalCounters).every(v=>v===0)));
const d=A.createTestOwnedDecision(envelope);
test(()=>assert.equal(A.evaluateSuppliedDecision(envelope,d),"AUTHORIZATION_APPROVED_PROJECTED"));
test(()=>assert.equal(A.projectReplayAgreement(p,A.projectAuthorizationReadiness(envelope)),"REPLAY_AGREEMENT"));
test(()=>assert.equal(A.projectReplayAgreement(p,{...p,canonical:"bad"}),"REPLAY_MISMATCH"));
code({scope:{...scope,capabilities:[]}},"SCOPE_INVALID");
code({requester:envelope.reviewer},"IDENTITY_CONFLICT");
code({lifecycle:{...lifecycle,expiresAt:"2026-07-28T00:00:00Z"}},"AUTHORIZATION_EXPIRED");
code({lifecycle:{...lifecycle,revoked:true}},"AUTHORIZATION_REVOKED");
code({lifecycle:{...lifecycle,suspended:true}},"AUTHORIZATION_SUSPENDED");
code({delegationAllowed:true},"DELEGATION_FORBIDDEN");
code({seals:{...envelope.seals,scope:"bad"}},"SEAL_BINDING_INVALID");
code({lifecycle:{...lifecycle,activatesAt:"2026-07-29T00:00:00Z"}},"LIFECYCLE_INVALID");
code({conflictOfInterest:true},"CONFLICT_OF_INTEREST");
test(()=>{let x;try{A.evaluateSuppliedDecision(envelope,{...d,controls:{...d.controls,AUTHORITY_SCOPE:false}})}catch(e){x=e}assert.equal(x?.code,"CONTROL_MISMATCH")});
for(const [name,expected] of [["createAuthorization", "AUTHORIZATION_CREATION_FORBIDDEN"], ["issueAuthorization", "AUTHORIZATION_ISSUANCE_FORBIDDEN"], ["activateAuthorization", "AUTHORIZATION_ACTIVATION_FORBIDDEN"], ["suspendAuthorization", "AUTHORIZATION_SUSPENSION_FORBIDDEN"], ["revokeAuthorization", "AUTHORIZATION_REVOCATION_FORBIDDEN"], ["renewAuthorization", "AUTHORIZATION_RENEWAL_FORBIDDEN"], ["delegateAuthorization", "AUTHORIZATION_DELEGATION_FORBIDDEN"], ["transferAuthorization", "AUTHORIZATION_TRANSFER_FORBIDDEN"], ["widenAuthorizationScope", "SCOPE_WIDENING_FORBIDDEN"], ["persistAuthorizationEnvelope", "AUTHORIZATION_PERSISTENCE_FORBIDDEN"], ["createControlledRunRequest", "CONTROLLED_RUN_REQUEST_CREATION_FORBIDDEN"], ["materializeExecutableBundle", "EXECUTABLE_BUNDLE_MATERIALIZATION_FORBIDDEN"], ["allocateWorkspace", "WORKSPACE_ALLOCATION_FORBIDDEN"], ["materializeInvocationPlan", "INVOCATION_PLAN_MATERIALIZATION_FORBIDDEN"], ["executeScenario", "SCENARIO_EXECUTION_FORBIDDEN"], ["constructOperationalCapture", "OPERATIONAL_CAPTURE_CONSTRUCTION_FORBIDDEN"], ["constructOperationalResult", "OPERATIONAL_RESULT_CONSTRUCTION_FORBIDDEN"], ["admitEvidence", "EVIDENCE_ADMISSION_FORBIDDEN"], ["mutateCandidateState", "CANDIDATE_STATE_MUTATION_FORBIDDEN"], ["executeCandidate", "CANDIDATE_EXECUTION_FORBIDDEN"], ["executeAdapter", "ADAPTER_EXECUTION_FORBIDDEN"], ["accessNetwork", "NETWORK_ACCESS_FORBIDDEN"], ["executeExternalProcess", "EXTERNAL_PROCESS_FORBIDDEN"], ["stageFoundation", "STAGE_FORBIDDEN"], ["commitFoundation", "COMMIT_FORBIDDEN"], ["tagFoundation", "TAG_FORBIDDEN"], ["pushFoundation", "PUSH_FORBIDDEN"]]){test(()=>{let x;try{A[name]()}catch(e){x=e}assert.equal(x?.code,expected)})}
assert.equal(cases,47);
console.log("NOOR_STEP_043_AUTHORIZATION_FOUNDATION_TESTS_PASS cases="+cases);
