export const SOURCE_CLASSES=["SRC-OFFICIAL","SRC-RELEASE","SRC-LICENSE","SRC-HOST","SRC-CONTROL","SRC-OPS"] as const;
export const COLLECTION_PHASES=["EC-01_AUTHORIZATION_AND_BASELINE_SEAL","EC-02_EVIDENCE_OBLIGATION_RESOLUTION","EC-03_SOURCE_TARGET_APPROVAL","EC-04_NETWORK_BOUNDARY_ACTIVATION","EC-05_RAW_SOURCE_RETRIEVAL","EC-06_CAPTURE_INTEGRITY_SEALING","EC-07_SOURCE_IDENTITY_AND_PROVENANCE_REVIEW","EC-08_CLAIM_EXTRACTION_AND_TRACEABILITY","EC-09_FRESHNESS_AND_APPLICABILITY_REVIEW","EC-10_CONFLICT_AND_CONFIDENCE_CLASSIFICATION","EC-11_EVIDENCE_BUNDLE_SEALING","EC-12_INDEPENDENT_REVIEW_AND_ATTESTATION"] as const;
export const ACCEPTANCE_GATES=["EG-01_AUTHORIZATION_AND_SCOPE","EG-02_SOURCE_IDENTITY","EG-03_PRIMARY_SOURCE_PREFERENCE","EG-04_NETWORK_CONTAINMENT","EG-05_CAPTURE_COMPLETENESS","EG-06_RAW_EVIDENCE_INTEGRITY","EG-07_CLAIM_TRACEABILITY","EG-08_FRESHNESS_AND_VERSION_APPLICABILITY","EG-09_CONFLICT_AND_CONFIDENCE_HANDLING","EG-10_LICENSE_AND_RETENTION_COMPLIANCE","EG-11_REDACTION_AND_CONFIDENTIALITY","EG-12_INDEPENDENT_REVIEW_AND_NON_MUTATION"] as const;
export const FAILURE_CODES=["AUTHORIZATION_MISSING","SCOPE_VIOLATION","BASELINE_MISMATCH","INVALID_COLLECTION_IDENTITY","INVALID_STATE_TRANSITION","EVIDENCE_OBLIGATION_MISMATCH","SOURCE_TARGET_INVALID","HOST_NOT_AUTHORIZED","NETWORK_ACCESS_DENIED","COLLECTION_CONTROLS_UNSELECTED","CAPTURE_INTEGRITY_FAILURE","CLAIM_TRACEABILITY_INCOMPLETE","FRESHNESS_UNRESOLVED","CONFLICT_UNRESOLVED","GATE_NOT_READY","MANIFEST_INCOMPLETE","RESULT_SEAL_MISMATCH","REPOSITORY_MUTATION_DETECTED"] as const;

export type Phase=(typeof COLLECTION_PHASES)[number];export type Failure=(typeof FAILURE_CODES)[number];export type SourceClass=(typeof SOURCE_CLASSES)[number];export type Gate=(typeof ACCEPTANCE_GATES)[number];
export interface Authorization{foundation:boolean;network:boolean;collection:boolean;screenshot:boolean;pdf:boolean;verification:boolean;experiment:boolean;mechanismRecommendation:boolean;mechanismSelection:boolean;mechanismImplementation:boolean;dependencyInstallation:boolean;candidateExecution:boolean;adapter:boolean;commit:boolean;tag:boolean;push:boolean}
export interface Intent{runId:string;obligationId:string;mechanismId:string;sourceClass:SourceClass;approvedHost:string;requirementsHash:string;designHash:string;landscapeHash:string;createdAt:string}
export interface Transition{from:Phase|null;to:Phase;at:string}export interface Snapshot{runId:string;phase:Phase;terminal:boolean;failure:Failure|null;transitions:readonly Transition[]}
export interface Controls{retrievalClient:string|null;hostAllowlist:string|null;redirectPolicy:string|null;contentTypes:string|null;captureFormat:string|null;claimLocations:string|null;freshnessWindow:string|null;retentionPolicy:string|null}
export interface Capture{id:string;contentType:string;bytes:number;sha256:string;retrievedAt:string;rawPreserved:true}export interface Claim{id:string;captureId:string;kind:"quotation"|"paraphrase"|"assumption"|"inference";text:string;location:string;confidence:"LOW"|"MEDIUM"|"HIGH"}export interface GateRecord{gate:Gate;state:"NOT_READY"|"PASS"|"FAIL";evidenceIds:readonly string[];blockers:readonly string[]}
export interface Manifest{schema:"1";intent:Intent;lifecycle:Snapshot;controls:Controls;captures:readonly Capture[];claims:readonly Claim[];gates:readonly GateRecord[];networkUsed:false;externalCollection:false;screenshot:false;pdf:false;verification:false;experiment:false;mechanismRecommendation:false;mechanismSelection:false;mechanismImplementation:false;dependencyInstallation:false;candidateExecution:false;adapter:false;repositoryMutation:false;commit:false;tag:false;push:false}
export class CollectionError extends Error{constructor(public readonly code:Failure,message:string){super(message);this.name="CollectionError"}}
const H=/^[a-f0-9]{64}$/u,R=/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/u,E=/^ES-(?:00[1-9]|0[1-9][0-9]|1[0-9]{2}|20[0-9]|21[0-6])$/u,M=/^ML-(?:ISO|NET|FS|MAT|IPC|CLK|RES|EVD|CLN)-0[1-4]$/u;
export function authorization():Authorization{return Object.freeze({foundation:true,network:false,collection:false,screenshot:false,pdf:false,verification:false,experiment:false,mechanismRecommendation:false,mechanismSelection:false,mechanismImplementation:false,dependencyInstallation:false,candidateExecution:false,adapter:false,commit:false,tag:false,push:false})}
export function assertFoundation(a:Authorization){if(!a.foundation)throw new CollectionError("AUTHORIZATION_MISSING","Foundation not authorized.");if(Object.entries(a).some(([k,v])=>k!=="foundation"&&v))throw new CollectionError("SCOPE_VIOLATION","Forbidden authorization.")}
export function assertCollection(a:Authorization){if(!a.network||!a.collection)throw new CollectionError("NETWORK_ACCESS_DENIED","External collection remains unauthorized.")}
export function validateIntent(i:Intent){if(!R.test(i.runId)||!E.test(i.obligationId)||!M.test(i.mechanismId)||!SOURCE_CLASSES.includes(i.sourceClass)||!i.approvedHost.trim())throw new CollectionError("INVALID_COLLECTION_IDENTITY","Invalid intent.");for(const x of[i.requirementsHash,i.designHash,i.landscapeHash])if(!H.test(x))throw new CollectionError("BASELINE_MISMATCH","Invalid hash.");if(Number.isNaN(Date.parse(i.createdAt)))throw new CollectionError("INVALID_COLLECTION_IDENTITY","Invalid time.")}
export class Lifecycle{#p:Phase=COLLECTION_PHASES[0];#t=false;#f:Failure|null=null;#x:Transition[]=[];constructor(readonly runId:string,readonly clock:()=>string){this.#x.push({from:null,to:this.#p,at:this.time()})}time(){const t=this.clock();if(Number.isNaN(Date.parse(t)))throw new CollectionError("INVALID_COLLECTION_IDENTITY","Invalid clock.");return t}advance(next:Phase){if(this.#t||next!==COLLECTION_PHASES[COLLECTION_PHASES.indexOf(this.#p)+1])throw new CollectionError("INVALID_STATE_TRANSITION","Invalid transition.");const from=this.#p;this.#p=next;this.#x.push({from,to:next,at:this.time()});if(next===COLLECTION_PHASES.at(-1))this.#t=true;return this.snapshot()}fail(f:Failure){if(this.#t)throw new CollectionError("INVALID_STATE_TRANSITION","Terminal.");this.#f=f;this.#t=true;return this.snapshot()}snapshot():Snapshot{return Object.freeze({runId:this.runId,phase:this.#p,terminal:this.#t,failure:this.#f,transitions:Object.freeze(this.#x.map(x=>Object.freeze({...x})))})}}
export function validateTarget(raw:string,hosts:readonly string[]){let u:URL;try{u=new URL(raw)}catch{throw new CollectionError("SOURCE_TARGET_INVALID","Invalid URL.")}if(u.protocol!=="https:"||u.username||u.password||u.hash)throw new CollectionError("SOURCE_TARGET_INVALID","Unsafe target.");const host=u.hostname.toLowerCase();if(!hosts.map(x=>x.toLowerCase()).includes(host))throw new CollectionError("HOST_NOT_AUTHORIZED","Host not allowed.");return Object.freeze({scheme:"https",host,path:u.pathname||"/",query:u.search,redirects:false})}
export function controls():Controls{return Object.freeze({retrievalClient:null,hostAllowlist:null,redirectPolicy:null,contentTypes:null,captureFormat:null,claimLocations:null,freshnessWindow:null,retentionPolicy:null})}export function assertControls(c:Controls){if(Object.values(c).some(v=>v===null||!v.trim()))throw new CollectionError("COLLECTION_CONTROLS_UNSELECTED","Controls unselected.")}
export function validateCapture(c:Capture,max:number,types:readonly string[]){if(!c.id.trim()||!types.includes(c.contentType)||!Number.isSafeInteger(c.bytes)||c.bytes<=0||c.bytes>max||!H.test(c.sha256)||c.rawPreserved!==true||Number.isNaN(Date.parse(c.retrievedAt)))throw new CollectionError("CAPTURE_INTEGRITY_FAILURE","Invalid capture.")}
export function validateClaim(c:Claim){if(!c.id.trim()||!c.captureId.trim()||!c.text.trim()||!c.location.trim())throw new CollectionError("CLAIM_TRACEABILITY_INCOMPLETE","Invalid claim.")}
export function validateGate(g:GateRecord){if(!ACCEPTANCE_GATES.includes(g.gate)||(g.state==="PASS"&&(g.evidenceIds.length===0||g.blockers.length))||(g.state==="NOT_READY"&&!g.blockers.length))throw new CollectionError("GATE_NOT_READY","Invalid gate.")}
const FORBIDDEN=new Set(["score","ranking","recommendation","selectedMechanism","selectedCandidate"]);function cv(v:unknown):unknown{if(Array.isArray(v))return v.map(cv);if(v!==null&&typeof v==="object"){const o:Record<string,unknown>={};for(const k of Object.keys(v as Record<string,unknown>).sort()){if(FORBIDDEN.has(k))throw new CollectionError("SCOPE_VIOLATION","Forbidden field.");const x=(v as Record<string,unknown>)[k];if(x!==undefined)o[k]=cv(x)}return o}if(v===null||["string","number","boolean"].includes(typeof v))return v;throw new CollectionError("MANIFEST_INCOMPLETE","Unsupported value.")}
export function canonical(v:unknown){const t=JSON.stringify(cv(v));if(t===undefined)throw new CollectionError("MANIFEST_INCOMPLETE","Serialization failed.");return t}export function validateManifest(m:Manifest){canonical(m);if(m.schema!=="1"||Object.entries(m).some(([k,v])=>["networkUsed","externalCollection","screenshot","pdf","verification","experiment","mechanismRecommendation","mechanismSelection","mechanismImplementation","dependencyInstallation","candidateExecution","adapter","repositoryMutation","commit","tag","push"].includes(k)&&v!==false))throw new CollectionError("SCOPE_VIOLATION","Invalid manifest.")}export function validateSeal(text:string,digest:string){if(!text||!H.test(digest))throw new CollectionError("RESULT_SEAL_MISMATCH","Invalid seal.")}
