export const EXECUTION_CONTROL_DOMAINS=["Retrieval Client","Host Allowlist Representation","Redirect Policy","Content-Type Allowlist","Per-Request Timeout","Per-Source Byte Limit","Capture File-Count Limit","HTML Capture Method","PDF Capture Method","Dynamic-Page Rendering Policy","Screenshot Capture Format","Raw Evidence Bundle Format","Claim-Location Representation","Confidence Vocabulary","Freshness Validity Window","Conflict-Escalation Policy","Redaction Representation","Evidence Retention and Expiry"] as const;
export const CONCEPT_FAMILIES=["NATIVE","DECLARATIVE","ISOLATED","OFFLINE"] as const;
export const REGISTRATION_PHASES=["OR-01_AUTHORIZATION_AND_BASELINE_SEAL","OR-02_REGISTRATION_SCHEMA_FREEZE","OR-03_CANDIDATE_IDENTITY_INTAKE","OR-04_CONTROL_DOMAIN_AND_CONCEPT_BINDING","OR-05_PRODUCT_MECHANISM_AND_PROVIDER_CLASSIFICATION","OR-06_VERSION_BUILD_AND_DISTRIBUTION_BINDING","OR-07_PROVENANCE_OWNERSHIP_AND_LICENSE_DECLARATION","OR-08_MAINTENANCE_AND_LIFECYCLE_DECLARATION","OR-09_HOST_RUNTIME_ARCHITECTURE_AND_PRIVILEGE_DECLARATION","OR-10_CAPABILITY_DEPENDENCY_AND_SUPPLY_CHAIN_DECLARATION","OR-11_NETWORK_BROWSER_PDF_SCREENSHOT_AND_AMBIENT_AUTHORITY_DECLARATION","OR-12_EVIDENCE_REFERENCE_AND_APPLICABILITY_BINDING","OR-13_DUPLICATE_CONFLICT_AND_SUPERSESSION_RESOLUTION","OR-14_REGISTRATION_STATE_AND_QUARANTINE_EVALUATION","OR-15_MANIFEST_SEAL_AND_NON_MUTATION_ATTESTATION","OR-16_INDEPENDENT_REVIEW_AND_REGISTRATION_AUTHORIZATION"] as const;
export const REGISTRATION_GATES=["OG-01_AUTHORIZATION_AND_REGISTRATION_SCOPE","OG-02_CANDIDATE_STABLE_IDENTITY","OG-03_CONTROL_DOMAIN_AND_CONCEPT_FAMILY_BINDING","OG-04_PRODUCT_MECHANISM_AND_PROVIDER_CLASSIFICATION","OG-05_VERSION_BUILD_AND_DISTRIBUTION_IDENTITY","OG-06_PROVENANCE_OWNERSHIP_AND_CUSTODY","OG-07_LICENSE_USAGE_AND_REDISTRIBUTION_RIGHTS","OG-08_MAINTENANCE_RELEASE_AND_LIFECYCLE_STATUS","OG-09_HOST_ARCHITECTURE_RUNTIME_AND_PRIVILEGE_APPLICABILITY","OG-10_DECLARED_AND_PROHIBITED_CAPABILITIES","OG-11_DEPENDENCY_AND_SUPPLY_CHAIN_DECLARATION","OG-12_NETWORK_DNS_BROWSER_PDF_AND_SCREENSHOT_DECLARATION","OG-13_FILESYSTEM_PROCESS_SECRET_AND_AMBIENT_AUTHORITY_DECLARATION","OG-14_EVIDENCE_REFERENCES_APPLICABILITY_AND_CONFIDENCE","OG-15_DUPLICATE_ALIAS_CONFLICT_AND_SUPERSESSION_HANDLING","OG-16_REGISTRATION_STATE_MACHINE_AND_TRANSITION_AUTHORITY","OG-17_WITHDRAWAL_DEPRECATION_REVOCATION_AND_QUARANTINE","OG-18_MANIFEST_SEALING_INDEPENDENT_REVIEW_AND_NON_MUTATION"] as const;
export const REGISTRATION_STATES=["DRAFT","QUARANTINED","REVIEW_READY","APPROVED","REJECTED","WITHDRAWN","DEPRECATED","REVOKED"] as const;
export const CAPABILITY_KEYS=["network","dns","browser","pdf","screenshot","filesystemRead","filesystemWrite","processSpawn","environmentRead","secretRead","credentialReuse","ambientAuthority"] as const;
export const FAILURE_CODES=["AUTHORIZATION_MISSING","SCOPE_VIOLATION","BASELINE_MISMATCH","INVALID_REGISTRATION_IDENTITY","INVALID_REVISION_IDENTITY","INVALID_STATE_TRANSITION","IDENTITY_INCOMPLETE","DOMAIN_BINDING_INVALID","PRODUCT_CLASSIFICATION_INCOMPLETE","VERSION_DISTRIBUTION_INCOMPLETE","PROVENANCE_INCOMPLETE","LICENSE_INCOMPLETE","LIFECYCLE_INCOMPLETE","HOST_APPLICABILITY_INCOMPLETE","CAPABILITY_DECLARATION_INCOMPLETE","UNDECLARED_CAPABILITY","AMBIENT_AUTHORITY_FORBIDDEN","DEPENDENCY_DECLARATION_INCOMPLETE","SUPPLY_CHAIN_INCOMPLETE","EVIDENCE_REFERENCE_INCOMPLETE","DUPLICATE_ALIAS_CONFLICT","SUPERSESSION_INVALID","QUARANTINE_REQUIRED","GATE_NOT_READY","MANIFEST_CREATION_FORBIDDEN","CANONICALIZATION_FAILURE","RESULT_SEAL_MISMATCH","REPOSITORY_MUTATION_DETECTED"] as const;
export type Domain=(typeof EXECUTION_CONTROL_DOMAINS)[number];export type Family=(typeof CONCEPT_FAMILIES)[number];export type Phase=(typeof REGISTRATION_PHASES)[number];export type Gate=(typeof REGISTRATION_GATES)[number];export type State=(typeof REGISTRATION_STATES)[number];export type Cap=(typeof CAPABILITY_KEYS)[number];export type Failure=(typeof FAILURE_CODES)[number];
export class RegistrationError extends Error{constructor(public readonly code:Failure,message:string){super(message);this.name="RegistrationError";}}
export interface Authorization{foundation:true;operationalRegistration:false;manifestCreation:false;evidenceCollection:false;experiment:false;scoring:false;ranking:false;recommendation:false;selection:false;implementation:false;dependencyInstallation:false;candidateInstallation:false;candidateExecution:false;network:false;dns:false;browser:false;pdf:false;screenshot:false;processExecution:false;adapter:false;commit:false;tag:false;push:false;}
export interface Baseline{registrationRunId:string;requirementsHash:string;designHash:string;foundationHash:string;createdAt:string;}
export interface Identity{candidateId:string;revisionId:string;controlDomain:Domain;conceptFamily:Family;conceptLineageId:string;productName:string;mechanismName:string;providerName:string;version:string;build:string;distribution:string;}
export interface Provenance{provenanceOwner:string;custodian:string;sourceIdentity:string;licenseIdentifier:string;usageRights:string;redistributionRights:string;noticeObligations:string;maintenanceStatus:string;releaseStatus:string;securityNoticeStatus:string;observedAt:string;}
export interface Host{hostOS:"macOS";architectures:readonly string[];runtimes:readonly string[];requiredPrivileges:readonly string[];sandboxExpected:true;}
export type Capabilities=Readonly<Record<Cap,boolean>>;
export interface Dependency{dependencyId:string;relationship:"DIRECT"|"TRANSITIVE"|"OPTIONAL"|"BUNDLED"|"RUNTIME";provider:string;sourceIdentity:string;version:string;integritySha256:string;licenseIdentifier:string;maintenanceStatus:string;}
export interface Evidence{evidenceId:string;sourceClass:string;sourceLocation:string;sourceDigest:string;observedAt:string;versionApplicability:string;hostApplicability:string;confidence:"UNVERIFIED"|"LOW"|"MEDIUM"|"HIGH";}
export interface GateRecord{gate:Gate;state:"NOT_READY"|"PASS"|"FAIL";evidenceIds:readonly string[];blockers:readonly string[];}
const HASH=/^[a-f0-9]{64}$/u,ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/u,CONCEPT=/^CC-027-\d{3}$/u,FORBIDDEN=new Set(["score","scores","rank","ranking","recommendation","recommendedCandidate","selectedCandidate","selectedMechanism"]);
function fail(c:Failure,m:string):never{throw new RegistrationError(c,m)}function req(v:string,c:Failure){if(!v.trim())fail(c,"Blank required value.")}function time(v:string,c:Failure){if(Number.isNaN(Date.parse(v)))fail(c,"Invalid timestamp.")}function uniq(v:readonly string[],c:Failure){if(v.some(x=>!x.trim())||new Set(v).size!==v.length)fail(c,"Blank or duplicate value.")}
export function foundationAuthorization():Authorization{return Object.freeze({foundation:true,operationalRegistration:false,manifestCreation:false,evidenceCollection:false,experiment:false,scoring:false,ranking:false,recommendation:false,selection:false,implementation:false,dependencyInstallation:false,candidateInstallation:false,candidateExecution:false,network:false,dns:false,browser:false,pdf:false,screenshot:false,processExecution:false,adapter:false,commit:false,tag:false,push:false})}
export function assertFoundationAuthorization(v:Authorization){if(!v.foundation)fail("AUTHORIZATION_MISSING","Foundation authorization missing.");if(Object.entries(v).some(([k,x])=>k!=="foundation"&&x))fail("SCOPE_VIOLATION","Authorization exceeds Step 029.")}
export function assertOperationalRegistration(v:Authorization):never{if(!v.operationalRegistration)fail("AUTHORIZATION_MISSING","Operational registration unauthorized.");return fail("SCOPE_VIOLATION","Step 029 cannot register a candidate.")}
export function assertManifestCreation(v:Authorization):never{if(!v.manifestCreation)fail("MANIFEST_CREATION_FORBIDDEN","Registration manifest creation unauthorized.");return fail("SCOPE_VIOLATION","Step 029 cannot create a registration manifest.")}
export function validateBaseline(v:Baseline){if(!ID.test(v.registrationRunId))fail("INVALID_REGISTRATION_IDENTITY","Invalid run identity.");for(const x of[v.requirementsHash,v.designHash,v.foundationHash])if(!HASH.test(x))fail("BASELINE_MISMATCH","Invalid baseline digest.");time(v.createdAt,"INVALID_REGISTRATION_IDENTITY")}
export function validateIdentity(v:Identity){if(!ID.test(v.candidateId))fail("INVALID_REGISTRATION_IDENTITY","Invalid candidate identity.");if(!ID.test(v.revisionId))fail("INVALID_REVISION_IDENTITY","Invalid revision identity.");if(!EXECUTION_CONTROL_DOMAINS.includes(v.controlDomain)||!CONCEPT_FAMILIES.includes(v.conceptFamily)||!CONCEPT.test(v.conceptLineageId))fail("DOMAIN_BINDING_INVALID","Invalid domain binding.");for(const x of[v.productName,v.mechanismName,v.providerName])req(x,"PRODUCT_CLASSIFICATION_INCOMPLETE");for(const x of[v.version,v.build,v.distribution])req(x,"VERSION_DISTRIBUTION_INCOMPLETE")}
export function validateProvenance(v:Provenance){for(const x of[v.provenanceOwner,v.custodian,v.sourceIdentity])req(x,"PROVENANCE_INCOMPLETE");for(const x of[v.licenseIdentifier,v.usageRights,v.redistributionRights,v.noticeObligations])req(x,"LICENSE_INCOMPLETE");for(const x of[v.maintenanceStatus,v.releaseStatus,v.securityNoticeStatus])req(x,"LIFECYCLE_INCOMPLETE");time(v.observedAt,"LIFECYCLE_INCOMPLETE")}
export function validateHost(v:Host){if(v.hostOS!=="macOS"||!v.sandboxExpected)fail("HOST_APPLICABILITY_INCOMPLETE","Invalid host boundary.");uniq(v.architectures,"HOST_APPLICABILITY_INCOMPLETE");uniq(v.runtimes,"HOST_APPLICABILITY_INCOMPLETE");uniq(v.requiredPrivileges,"HOST_APPLICABILITY_INCOMPLETE")}
export function validateCapabilities(v:Readonly<Partial<Record<Cap,boolean>>>):Capabilities{const o={} as Record<Cap,boolean>;for(const k of CAPABILITY_KEYS){const x=v[k];if(typeof x!=="boolean")fail("UNDECLARED_CAPABILITY",`Capability is undeclared: ${k}.`);o[k]=x}if(o.ambientAuthority||o.credentialReuse)fail("AMBIENT_AUTHORITY_FORBIDDEN","Ambient authority is forbidden.");return Object.freeze(o)}
export function validateDependencies(v:readonly Dependency[]){const ids:string[]=[];for(const x of v){for(const y of[x.dependencyId,x.provider,x.sourceIdentity,x.version,x.licenseIdentifier,x.maintenanceStatus])req(y,"DEPENDENCY_DECLARATION_INCOMPLETE");if(!HASH.test(x.integritySha256))fail("SUPPLY_CHAIN_INCOMPLETE","Invalid dependency digest.");ids.push(x.dependencyId)}if(new Set(ids).size!==ids.length)fail("DUPLICATE_ALIAS_CONFLICT","Duplicate dependency identity.")}
export function validateEvidence(v:readonly Evidence[]){const ids:string[]=[];for(const x of v){for(const y of[x.evidenceId,x.sourceClass,x.sourceLocation,x.versionApplicability,x.hostApplicability])req(y,"EVIDENCE_REFERENCE_INCOMPLETE");if(!HASH.test(x.sourceDigest))fail("EVIDENCE_REFERENCE_INCOMPLETE","Invalid evidence digest.");time(x.observedAt,"EVIDENCE_REFERENCE_INCOMPLETE");ids.push(x.evidenceId)}if(new Set(ids).size!==ids.length)fail("DUPLICATE_ALIAS_CONFLICT","Duplicate evidence identity.")}
export function validateSupersession(v:{revisionId:string;supersedesRevisionId:string|null}){if(!ID.test(v.revisionId))fail("INVALID_REVISION_IDENTITY","Invalid revision identity.");if(v.supersedesRevisionId!==null&&(!ID.test(v.supersedesRevisionId)||v.supersedesRevisionId===v.revisionId))fail("SUPERSESSION_INVALID","Invalid supersession.")}
const TRANS={DRAFT:["QUARANTINED","REVIEW_READY","WITHDRAWN"],QUARANTINED:["REJECTED","WITHDRAWN"],REVIEW_READY:["QUARANTINED","APPROVED","REJECTED","WITHDRAWN"],APPROVED:["DEPRECATED","REVOKED"],REJECTED:[],WITHDRAWN:[],DEPRECATED:["REVOKED"],REVOKED:[]} as const satisfies Readonly<Record<State,readonly State[]>>;
export class RegistrationLifecycle{#phase:Phase=REGISTRATION_PHASES[0];#state:State="DRAFT";#terminal=false;#failure:Failure|null=null;#pt:{from:Phase|null;to:Phase;at:string}[]=[];#st:{from:State;to:State;at:string}[]=[];constructor(readonly registrationRunId:string,readonly clock:()=>string){if(!ID.test(registrationRunId))fail("INVALID_REGISTRATION_IDENTITY","Invalid run identity.");this.#pt.push({from:null,to:this.#phase,at:this.now()})}private now(){const x=this.clock();time(x,"INVALID_REGISTRATION_IDENTITY");return x}advancePhase(next:Phase){const expected=REGISTRATION_PHASES[REGISTRATION_PHASES.indexOf(this.#phase)+1];if(this.#terminal||next!==expected)fail("INVALID_STATE_TRANSITION","Invalid phase transition.");const from=this.#phase;this.#phase=next;this.#pt.push({from,to:next,at:this.now()});if(next===REGISTRATION_PHASES.at(-1))this.#terminal=true;return this.snapshot()}transitionState(next:State){const allowed:readonly State[]=TRANS[this.#state];if(this.#terminal||!allowed.includes(next))fail("INVALID_STATE_TRANSITION","Invalid state transition.");const from=this.#state;this.#state=next;this.#st.push({from,to:next,at:this.now()});return this.snapshot()}quarantine(code:Failure){if(this.#terminal)fail("INVALID_STATE_TRANSITION","Terminal lifecycle.");const from=this.#state;this.#state="QUARANTINED";this.#failure=code;this.#st.push({from,to:"QUARANTINED",at:this.now()});return this.snapshot()}snapshot(){return Object.freeze({registrationRunId:this.registrationRunId,phase:this.#phase,state:this.#state,terminal:this.#terminal,failure:this.#failure,phaseTransitions:Object.freeze(this.#pt.map(x=>Object.freeze({...x}))),stateTransitions:Object.freeze(this.#st.map(x=>Object.freeze({...x})))})}}
export function validateGate(v:GateRecord){if(!REGISTRATION_GATES.includes(v.gate))fail("GATE_NOT_READY","Unknown gate.");if(v.state==="PASS"&&(!v.evidenceIds.length||v.blockers.length))fail("GATE_NOT_READY","Invalid passing gate.");if(v.state==="NOT_READY"&&!v.blockers.length)fail("GATE_NOT_READY","Missing blockers.")}
function cv(v:unknown):unknown{if(Array.isArray(v))return v.map(cv);if(v!==null&&typeof v==="object"){const o:Record<string,unknown>={};for(const k of Object.keys(v as Record<string,unknown>).sort()){if(FORBIDDEN.has(k))fail("SCOPE_VIOLATION",`Forbidden field: ${k}.`);const x=(v as Record<string,unknown>)[k];if(x!==undefined)o[k]=cv(x)}return o}if(v===null||typeof v==="string"||typeof v==="number"||typeof v==="boolean")return v;return fail("CANONICALIZATION_FAILURE","Unsupported value.")}
export function canonicalize(v:unknown){const x=JSON.stringify(cv(v));if(x===undefined)fail("CANONICALIZATION_FAILURE","Serialization failed.");return x}export function validateSeal(t:string,d:string){if(!t||!HASH.test(d))fail("RESULT_SEAL_MISMATCH","Invalid seal.")}
