import {CANDIDATE_IDS,RUNTIME_PHASES,type Authorization,type Controls,type IpcRequest,type LifecycleSnapshot,type Limits,type Manifest,type RunIntent,type RuntimeFailureCode,type RuntimePhase,type Transition,type Workspace} from "./contracts.js";
export class RuntimeError extends Error{constructor(public readonly code:RuntimeFailureCode,message:string,public readonly details:Readonly<Record<string,unknown>>={}){super(message);this.name="RuntimeError"}}
const HASH=/^[a-f0-9]{64}$/u, ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/u, SENSITIVE=/(?:TOKEN|SECRET|PASSWORD|PASSWD|COOKIE|AUTH|CREDENTIAL|PRIVATE|PROXY|AWS_|AZURE_|GCP_|GOOGLE_|GITHUB_|GITLAB_|NPM_|YARN_)/iu;
export function authorization():Authorization{return Object.freeze({runtimeFoundationImplementation:true,candidateInstallation:false,candidateExecution:false,candidateSelection:false,dependencySelection:false,productionAdapterImplementation:false,commit:false,tag:false,push:false})}
export function assertFoundation(a:Authorization){if(!a.runtimeFoundationImplementation)throw new RuntimeError("AUTHORIZATION_MISSING","Runtime foundation is not authorized.");if([a.candidateInstallation,a.candidateExecution,a.candidateSelection,a.dependencySelection,a.productionAdapterImplementation,a.commit,a.tag,a.push].some(Boolean))throw new RuntimeError("SCOPE_VIOLATION","Forbidden authorization capability.")}
export function assertCandidateExecution(a:Authorization){if(!a.candidateExecution)throw new RuntimeError("AUTHORIZATION_MISSING","Candidate execution is not authorized.")}
export function validateIntent(i:RunIntent){if(!ID.test(i.runId))throw new RuntimeError("INVALID_RUN_IDENTITY","Invalid run ID.");if(!CANDIDATE_IDS.includes(i.candidateId))throw new RuntimeError("COHORT_MISMATCH","Candidate outside cohort.");if(!i.fixtureId.trim())throw new RuntimeError("FIXTURE_INTEGRITY_FAILURE","Empty fixture ID.");for(const v of [i.requirementsHash,i.designHash,i.protocolHash,i.foundationHash])if(!HASH.test(v))throw new RuntimeError("BASELINE_MISMATCH","Invalid governing hash.");if(Number.isNaN(Date.parse(i.createdAt)))throw new RuntimeError("INVALID_RUN_IDENTITY","Invalid createdAt.")}
export class Lifecycle{#phase:RuntimePhase=RUNTIME_PHASES[0];#terminal=false;#primary:RuntimeFailureCode|null=null;#secondary:RuntimeFailureCode[]=[];#transitions:Transition[]=[];constructor(readonly runId:string,readonly clock:()=>string){const t=clock();if(Number.isNaN(Date.parse(t)))throw new RuntimeError("INVALID_RUN_IDENTITY","Invalid controller clock.");this.#transitions.push({from:null,to:this.#phase,controllerTimestamp:t})}advance(next:RuntimePhase):LifecycleSnapshot{if(this.#terminal)throw new RuntimeError("INVALID_STATE_TRANSITION","Terminal lifecycle.");const expected=RUNTIME_PHASES[RUNTIME_PHASES.indexOf(this.#phase)+1];if(next!==expected)throw new RuntimeError("INVALID_STATE_TRANSITION","Only next phase allowed.");const t=this.clock();if(Number.isNaN(Date.parse(t)))throw new RuntimeError("INVALID_RUN_IDENTITY","Invalid controller clock.");const from=this.#phase;this.#phase=next;this.#transitions.push({from,to:next,controllerTimestamp:t});if(next===RUNTIME_PHASES.at(-1))this.#terminal=true;return this.snapshot()}fail(f:RuntimeFailureCode,s:readonly RuntimeFailureCode[]=[]){if(this.#terminal)throw new RuntimeError("INVALID_STATE_TRANSITION","Terminal lifecycle.");this.#primary=f;this.#secondary=[...new Set(s)].filter(x=>x!==f);this.#terminal=true;return this.snapshot()}snapshot():LifecycleSnapshot{return Object.freeze({runId:this.runId,phase:this.#phase,terminal:this.#terminal,primaryFailure:this.#primary,secondaryFailures:Object.freeze([...this.#secondary]),transitions:Object.freeze(this.#transitions.map(x=>Object.freeze({...x})))})}}
function norm(v:string){if(!v.startsWith('/'))throw new RuntimeError("WORKSPACE_NOT_ISOLATED","Absolute path required.");const a:string[]=[];for(const x of v.split('/')){if(!x||x==='.')continue;if(x==='..'){if(!a.length)throw new RuntimeError("WORKSPACE_NOT_ISOLATED","Path escape.");a.pop()}else a.push(x)}return '/'+a.join('/')}
export function workspace(rootValue:string,protectedValues:readonly string[]):Workspace{const root=norm(rootValue);for(const p0 of protectedValues){const p=norm(p0),pp=p==='/'?'/':p+'/',rp=root==='/'?'/':root+'/';if(root===p||root.startsWith(pp)||p.startsWith(rp))throw new RuntimeError("WORKSPACE_NOT_ISOLATED","Protected path overlap.")}const child=(n:string)=>root==='/'?'/'+n:root+'/'+n;return Object.freeze({root,inputDirectory:child('input'),packageDirectory:child('package'),outputDirectory:child('output'),telemetryDirectory:child('telemetry'),sealDirectory:child('seal')})}
export function assertUnused(entries:readonly string[]){if(entries.length)throw new RuntimeError("WORKSPACE_REUSE_DETECTED","Workspace must be empty.")}
export function environment(source:Readonly<Record<string,string|undefined>>,allow:readonly string[],fixed:Readonly<Record<string,string>>){const ok=new Set(allow),e:Record<string,string>={},removed=new Set<string>();for(const [k,v] of Object.entries(source)){if(v!==undefined&&ok.has(k)&&!SENSITIVE.test(k))e[k]=v;else removed.add(k)}for(const [k,v] of Object.entries(fixed)){if(!ok.has(k)||SENSITIVE.test(k))throw new RuntimeError("ENVIRONMENT_LEAK","Invalid deterministic key.");e[k]=v}return Object.freeze({effective:Object.freeze(Object.fromEntries(Object.entries(e).sort(([a],[b])=>a.localeCompare(b)))),removedKeys:Object.freeze([...removed].sort())})}
export function validateLimits(l:Limits){for(const [k,v] of Object.entries(l)){if(k==='automaticRetry')continue;if(!Number.isSafeInteger(v)||Number(v)<=0)throw new RuntimeError("RESOURCE_LIMIT_EXCEEDED",k+' must be positive.')}if(l.automaticRetry!==false)throw new RuntimeError("SCOPE_VIOLATION","Automatic retry forbidden.")}
export function validateIpc(r:IpcRequest,max:number){if(r.schemaVersion!=="1"||!ID.test(r.runId)||!HASH.test(r.payloadSha256)||!r.protocolVersion.trim())throw new RuntimeError("IPC_HANDSHAKE_FAILURE","Invalid IPC envelope.");if(!Number.isSafeInteger(r.payloadBytes)||r.payloadBytes<0||!Number.isSafeInteger(max)||max<=0||r.payloadBytes>max)throw new RuntimeError("RESOURCE_LIMIT_EXCEEDED","IPC size limit exceeded.")}
export function controls():Controls{return Object.freeze({isolationSubstrate:null,networkDenialMechanism:null,filesystemRestrictionMechanism:null,ipcTransport:null,clockControlMechanism:null})}
export function assertControls(c:Controls){if(Object.values(c).some(v=>v===null||!v.trim()))throw new RuntimeError("NETWORK_DENIAL_UNPROVEN","Runtime mechanisms remain unselected; fail closed.")}
const FORBIDDEN=new Set(['score','scores','rank','ranking','recommendation','recommendedCandidate','selectedCandidate','gateQualification']);
function canon(v:unknown):unknown{if(Array.isArray(v))return v.map(canon);if(v!==null&&typeof v==='object'){const r:Record<string,unknown>={};for(const k of Object.keys(v as Record<string,unknown>).sort()){if(FORBIDDEN.has(k))throw new RuntimeError("SCOPE_VIOLATION",'Forbidden evidence field: '+k);const x=(v as Record<string,unknown>)[k];if(x!==undefined)r[k]=canon(x)}return r}if(['string','number','boolean'].includes(typeof v)||v===null)return v;throw new RuntimeError("EVIDENCE_INCOMPLETE","Unsupported evidence value.")}
export function canonical(v:unknown){const s=JSON.stringify(canon(v));if(s===undefined)throw new RuntimeError("EVIDENCE_INCOMPLETE","Serialization failed.");return s}
export function validateManifest(m:Manifest){canonical(m);if(m.schemaVersion!=="1")throw new RuntimeError("EVIDENCE_INCOMPLETE","Invalid schema.");if(m.repositoryMutation!==false||m.networkUsed!==false||m.dependencyInstallation!==false||m.candidateInstallation!==false||m.candidateExecution!==false||m.candidateSelection!==false||m.dependencySelection!==false||m.productionAdapterImplementation!==false||m.commit!==false||m.tag!==false||m.push!==false)throw new RuntimeError("SCOPE_VIOLATION","Unauthorized affirmative evidence.")}
export function validateSeal(text:string,digest:string){if(!text||!HASH.test(digest))throw new RuntimeError("RESULT_SEAL_MISMATCH","Invalid external seal.")}
